"""Módulo dedicado contener las principales configuraciones de la librería"""
from finrisklib.enums import Currency
from finrisklib.enums import Locality
from finrisklib.enums import CurveType
from finrisklib.enums import FinancialIndex

# region Clientes CSA

"""Clientes CSA"""
csa_clients = {'964890005': 'CREDICORP CAPITAL CORREDORES DE BOLSA SPA',
               '0970060006': 'BANCO DE CREDITO E INVERSIONES',
               '0970180001': 'SCOTIABANK CHILE',
               '0970300007': 'BANCO DEL ESTADO DE CHILE',
               '097036000K': 'BANCO SANTANDER CHILE',
               '0970430008': 'JP MORGAN CHASE BANK',
               # '0970530002': 'BANCO SECURITY',
               # '097080000K': 'BANCO BICE',
               '4038302766': 'BARCLAYS BANK PLC LONDRES',
               '4042672403': 'BBVA ESPAÑA',
               '4076552687': 'BNP PARIBAS FRANCIA',
               '4078408281': 'BANK OF AMERICA NA',
               '408404268K': 'BNP PARIBAS - FRANCIA',
               '4525472766': 'JP MORGAN CHASE BANK NA UK',
               '4526122769': 'CITIBANK NA LONDON',
               '4531832766': 'HSBC BANK PLC',
               '453423276K': 'MERRILL LYNCH INTERNATIONAL',
               '4537958281': 'HSBC USA',
               '4563121365': 'THE BANK OF NOVA SCOTIA (SCOTIABANK)',
               '4586912769': 'GOLDMAN SACHS INTL LONDON',
               '4591652767': 'LCHCLEARNET LIMITED',
               '4631808285': 'GOLDMAN SACHS USA',
               '4661572766': 'MORGAN STANLEY COINTLPLC',
               '480256200K': 'UBS - SUIZA',
               '4959212762': 'WELLS FARGO BNAK LONDON',
               # '763620999': 'BANCO BTG PACTUAL CHILE',
               '965096604': 'BANCO FALABELLA SA',
               '970060006': 'BANCO DE CREDITO E INVERSIONES',
               '970110003': 'BANCO INTERNACIONAL',
               '970180001': 'SCOTIABANK CHILE',
               '970300007': 'BANCO DEL ESTADO DE CHILE',
               '97036000K': 'BANCO SANTANDER CHILE',
               '970430008': 'JP MORGAN CHASE BANK',
               # '970530002': 'BANCO SECURITY',
               # '97080000K': 'BANCO BICE',
               # '979510004': 'HSBC BANK CHILE',
               '995004100': 'BANCO CONSORCIO',
               '200508258K': 'CHICAGO MERCANTILE EXCHANGE - CME',
               '828789007':	'COOPERATIVA DE AHORRO Y CREDITO COOPEUCH',
               '4159492767': 'DEUTSCHE BANK UK'
               }

# endregion

#  region Configuración de pares de moneda

"""Pares de Monedas"""
fx_pair_config = {
    'USDCLP': {'primary': 'USD', 'secondary': 'CLP', 'discount days': 1, 'calendar': [Locality.CHL, Locality.USA]},
    'USDCOP': {'primary': 'USD', 'secondary': 'COP', 'discount days': 2, 'calendar': [Locality.USA]},
    'USDPEN': {'primary': 'USD', 'secondary': 'PEN', 'discount days': 2, 'calendar': [Locality.USA]},
    'USDBRL': {'primary': 'USD', 'secondary': 'BRL', 'discount days': 2, 'calendar': [Locality.USA]},
    'USDMXN': {'primary': 'USD', 'secondary': 'MXN', 'discount days': 2, 'calendar': [Locality.USA]},
    'USDCAD': {'primary': 'USD', 'secondary': 'CAD', 'discount days': 1, 'calendar': [Locality.USA]},
    'USDNOK': {'primary': 'USD', 'secondary': 'NOK', 'discount days': 2, 'calendar': [Locality.USA]},
    'USDDKK': {'primary': 'USD', 'secondary': 'DKK', 'discount days': 2, 'calendar': [Locality.USA]},
    'USDSEK': {'primary': 'USD', 'secondary': 'SEK', 'discount days': 2, 'calendar': [Locality.USA]},
    'USDCHF': {'primary': 'USD', 'secondary': 'CHF', 'discount days': 2, 'calendar': [Locality.USA]},
    'USDJPY': {'primary': 'USD', 'secondary': 'JPY', 'discount days': 2, 'calendar': [Locality.USA]},
    'USDKRW': {'primary': 'USD', 'secondary': 'KRW', 'discount days': 2, 'calendar': [Locality.USA]},
    'USDCNY': {'primary': 'USD', 'secondary': 'CNY', 'discount days': 2, 'calendar': [Locality.USA]},
    'USDCNH': {'primary': 'USD', 'secondary': 'CNH', 'discount days': 2, 'calendar': [Locality.USA]},
    'USDAUD': {'primary': 'USD', 'secondary': 'AUD', 'discount days': 2, 'calendar': [Locality.USA]},
    'USDNZD': {'primary': 'USD', 'secondary': 'NZD', 'discount days': 2, 'calendar': [Locality.USA]},
    'USDZAR': {'primary': 'USD', 'secondary': 'ZAR', 'discount days': 2, 'calendar': [Locality.USA]},
    'EURUSD': {'primary': 'EUR', 'secondary': 'USD', 'discount days': 2, 'calendar': [Locality.USA]},
    'GBPUSD': {'primary': 'GBP', 'secondary': 'USD', 'discount days': 2, 'calendar': [Locality.USA]},
    'CLFCLP': {'primary': 'CLF', 'secondary': 'CLP', 'discount days': 0, 'calendar': [Locality.CHL]},
    'CLPCLF': {'primary': 'CLP', 'secondary': 'CLF', 'discount days': 0, 'calendar': [Locality.CHL]},
    'CADUSD': {'primary': 'CAD', 'secondary': 'USD', 'discount days': 1, 'calendar': [Locality.USA]},
    'CLPUSD': {'primary': 'CLP', 'secondary': 'USD', 'discount days': 1, 'calendar': [Locality.CHL, Locality.USA]},
    'COPCLP': {'primary': 'COP', 'secondary': 'CLP', 'discount days': 2, 'calendar': [Locality.CHL, Locality.COL]}
}

# endregion

# region Configuración de Índices

"""Indices Financieros"""
index_config = {
    FinancialIndex.FIX: {'type': 'ON', 'period': 'ON', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.ICP: {'type': 'ON', 'period': 'ON', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.ICP_REAL: {'type': 'ON', 'period': 'ON', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.TAB1M: {'type': 'IBOR', 'period': 'MONTHLY', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.TAB3M: {'type': 'IBOR', 'period': 'QUARTERLY', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.TAB6M: {'type': 'IBOR', 'period': 'BIANNUAL', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.TAB1Y: {'type': 'IBOR', 'period': 'ANNUAL', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.TABUF3M: {'type': 'IBOR', 'period': 'QUARTERLY', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.TABUF6M: {'type': 'IBOR', 'period': 'BIANNUAL', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.TABUF1Y: {'type': 'IBOR', 'period': 'ANNUAL', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.OIS: {'type': 'ON', 'period': 'ON', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.SOFR: {'type': 'ON', 'period': 'ON', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.LIBOR1M: {'type': 'IBOR', 'period': 'MONTHLY', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.LIBOR3M: {'type': 'IBOR', 'period': 'QUARTERLY', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.LIBOR6M: {'type': 'IBOR', 'period': 'BIANNUAL', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.LIBOR1Y: {'type': 'IBOR', 'period': 'ANNUAL', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.TERM_SOFR1M: {'type': 'IBOR', 'period': 'MONTHLY', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.TERM_SOFR3M: {'type': 'IBOR', 'period': 'QUARTERLY', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.TERM_SOFR6M: {'type': 'IBOR', 'period': 'BIANNUAL', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.TERM_SOFR1Y: {'type': 'IBOR', 'period': 'ANNUAL', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.EONIA: {'type': 'ON', 'period': 'ON', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.ESTR: {'type': 'ON', 'period': 'ON', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.EURIBOR1M: {'type': 'IBOR', 'period': 'MONTHLY', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.EURIBOR3M: {'type': 'IBOR', 'period': 'QUARTERLY', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.EURIBOR6M: {'type': 'IBOR', 'period': 'BIANNUAL', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.EURIBOR1Y: {'type': 'IBOR', 'period': 'ANNUAL', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.IBR: {'type': 'ON', 'period': 'ON', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.TONA: {'type': 'ON', 'period': 'ON', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.BBSW_3M : {'type': 'IBOR', 'period': 'QUARTERLY', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.SARON: {'type': 'ON', 'period': 'ON', 'count': 'DC_ACT_360', 'compound': 'LINEAR'},
    FinancialIndex.AONIA: {'type': 'ON', 'period': 'ON', 'count': 'DC_ACT_360', 'compound': 'LINEAR'}
}


"""Códigos de Indices"""
index_codes = {'FIJA': FinancialIndex.FIX,
               'FIX': FinancialIndex.FIX,
               'CLICP INDEX': FinancialIndex.ICP,
               'ICP': FinancialIndex.ICP,
               'CLP TNA': FinancialIndex.ICP,
               'CLICREAL INDEX': FinancialIndex.ICP_REAL,
               'ICP REAL': FinancialIndex.ICP_REAL,
               'CLF TRA': FinancialIndex.ICP_REAL,
               'CLP TAB 1M': FinancialIndex.TAB1M,
               'CLTN30DN INDEX': FinancialIndex.TAB1M,
               'TAB CLP 30': FinancialIndex.TAB1M,
               'TAB30': FinancialIndex.TAB1M,
               'TAB 1M': FinancialIndex.TAB1M,
               'TAB CLP 1M': FinancialIndex.TAB1M,
               'TAB30.CLP': FinancialIndex.TAB1M,
               'CLP TAB 3M': FinancialIndex.TAB3M,
               'CLTN90DN INDEX': FinancialIndex.TAB3M,
               'TAB CLP 90': FinancialIndex.TAB3M,
               'TAB 3M': FinancialIndex.TAB3M,
               'TAB CLP 3M': FinancialIndex.TAB3M,
               'CLP TAB 6M': FinancialIndex.TAB6M,
               'CLTN180N INDEX': FinancialIndex.TAB6M,
               'TAB CLP 180': FinancialIndex.TAB6M,
               'TAB 6M': FinancialIndex.TAB6M,
               'TAB CLP 6M': FinancialIndex.TAB6M,
               'CLP TAB 1Y': FinancialIndex.TAB1Y,
               'CLTN360N INDEX': FinancialIndex.TAB1Y,
               'TAB CLP 360': FinancialIndex.TAB1Y,
               'TAB 1Y': FinancialIndex.TAB1Y,
               'TAB CLP 1Y': FinancialIndex.TAB1Y,
               'CLF TAB 3M': FinancialIndex.TABUF3M,
               'PCRR90D INDEX': FinancialIndex.TABUF3M,
               'TAB CLF 90': FinancialIndex.TABUF3M,
               'TAB CLF 3M': FinancialIndex.TABUF3M,
               'TABUF 3M': FinancialIndex.TABUF3M,
               'CLF TAB 6M': FinancialIndex.TABUF6M,
               'PCRR180D INDEX': FinancialIndex.TABUF6M,
               'TAB CLF 180': FinancialIndex.TABUF6M,
               'TAB CLF 6M': FinancialIndex.TABUF6M,
               'TABUF 6M': FinancialIndex.TABUF6M,
               'CLF TAB 1Y': FinancialIndex.TABUF1Y,
               'PCRR360D INDEX': FinancialIndex.TABUF1Y,
               'TAB CLF 360': FinancialIndex.TABUF1Y,
               'TAB CLF 1Y': FinancialIndex.TABUF1Y,
               'TABUF 1Y': FinancialIndex.TABUF1Y,
               'TAB360.CLF': FinancialIndex.TABUF1Y,
               'EUR EURIBOR 1M': FinancialIndex.EURIBOR1M,
               'EUR001M INDEX': FinancialIndex.EURIBOR1M,
               'EURIBOR 1M': FinancialIndex.EURIBOR1M,
               'EUR EURIBOR 3M': FinancialIndex.EURIBOR3M,
               'EUR003M INDEX': FinancialIndex.EURIBOR3M,
               'EURIBOR 3M': FinancialIndex.EURIBOR3M,
               'EUR EURIBOR 6M': FinancialIndex.EURIBOR6M,
               'EUR006M INDEX': FinancialIndex.EURIBOR6M,
               'EURIBOR 6M': FinancialIndex.EURIBOR6M,
               'EURIBOR6M': FinancialIndex.EURIBOR6M,
               'EURIBOR 180': FinancialIndex.EURIBOR6M,
               'EURIBOR180': FinancialIndex.EURIBOR6M,
               'EUR EURIBOR 1Y': FinancialIndex.EURIBOR1Y,
               'EUR012M INDEX': FinancialIndex.EURIBOR1Y,
               'EURIBOR 12M': FinancialIndex.EURIBOR1Y,
               'SOFRRATE INDEX': FinancialIndex.SOFR,
               'USD SOFR CMP': FinancialIndex.SOFR,
               'USD SOFR CMP -2BD': FinancialIndex.SOFR,
               'USD SOFR CMP 6M FALLBACK': FinancialIndex.SOFR,
               'SOFR': FinancialIndex.SOFR,
               'OIS': FinancialIndex.SOFR,
               'USD SOFR 1Y': FinancialIndex.TERM_SOFR1Y,
               'TSFR12M INDEX': FinancialIndex.TERM_SOFR1Y,
               'TERM SOFR 12M': FinancialIndex.TERM_SOFR1Y,
               'USD SOFR 1M': FinancialIndex.TERM_SOFR1M,
               'TSFR1M INDEX': FinancialIndex.TERM_SOFR1M,
               'TERM SOFR 1M': FinancialIndex.TERM_SOFR1M,
               'USD SOFR 3M': FinancialIndex.TERM_SOFR3M,
               'TSFR3M INDEX': FinancialIndex.TERM_SOFR3M,
               'TERM SOFR 3M': FinancialIndex.TERM_SOFR3M,
               'USD SOFR 6M': FinancialIndex.TERM_SOFR6M,
               'TSFR6M INDEX': FinancialIndex.TERM_SOFR6M,
               'TERM SOFR 6M': FinancialIndex.TERM_SOFR6M,
               'USD LIBOR 1M': FinancialIndex.LIBOR1M,
               'US0001M INDEX': FinancialIndex.LIBOR1M,
               'LIBOR US 1M': FinancialIndex.LIBOR1M,
               'LIBOR 1M': FinancialIndex.LIBOR1M,
               'LIBOR30': FinancialIndex.LIBOR1M,
               'LIBOR 30': FinancialIndex.LIBOR1M,
               'USD LIBOR 3M': FinancialIndex.LIBOR3M,
               'US0003M INDEX': FinancialIndex.LIBOR3M,
               'LIBOR US 3M': FinancialIndex.LIBOR3M,
               'LIBOR 3M': FinancialIndex.LIBOR3M,
               'LIBOR90': FinancialIndex.LIBOR3M,
               'LIBOR 90': FinancialIndex.LIBOR3M,
               'USD LIBOR 6M': FinancialIndex.LIBOR6M,
               'US0006M INDEX': FinancialIndex.LIBOR6M,
               'LIBOR US 6M': FinancialIndex.LIBOR6M,
               'LIBOR 6M': FinancialIndex.LIBOR6M,
               'LIBOR180': FinancialIndex.LIBOR6M,
               'LIBOR 180': FinancialIndex.LIBOR6M,
               'USD LIBOR 1Y': FinancialIndex.LIBOR1Y,
               'US0012M INDEX': FinancialIndex.LIBOR1Y,
               'LIBOR US 12M': FinancialIndex.LIBOR1Y,
               'LIBOR 12M': FinancialIndex.LIBOR1Y,
               'LIBOR360': FinancialIndex.LIBOR1Y,
               'LIBOR 360': FinancialIndex.LIBOR1Y
               }

"""Códigos BBG"""
index_bbg_codes = {FinancialIndex.ICP: 'CLICP INDEX',
                   FinancialIndex.ICP_REAL: 'CLICREAL INDEX',
                   FinancialIndex.TAB6M: 'CLTN180N INDEX',
                   FinancialIndex.TAB1M: 'CLTN30DN INDEX',
                   FinancialIndex.TAB1Y: 'CLTN360N INDEX',
                   FinancialIndex.TAB3M: 'CLTN90DN INDEX',
                   FinancialIndex.EURIBOR1M: 'EUR001M INDEX',
                   FinancialIndex.EURIBOR3M: 'EUR003M INDEX',
                   FinancialIndex.EURIBOR6M: 'EUR006M INDEX',
                   FinancialIndex.EURIBOR1Y: 'EUR012M INDEX',
                   FinancialIndex.TABUF6M: 'PCRR180D INDEX',
                   FinancialIndex.TABUF1Y: 'PCRR360D INDEX',
                   FinancialIndex.TABUF3M: 'PCRR90D INDEX',
                   FinancialIndex.SOFR: 'SOFRRATE INDEX',
                   FinancialIndex.TERM_SOFR1Y: 'TSFR12M INDEX',
                   FinancialIndex.TERM_SOFR1M: 'TSFR1M INDEX',
                   FinancialIndex.TERM_SOFR3M: 'TSFR3M INDEX',
                   FinancialIndex.TERM_SOFR6M: 'TSFR6M INDEX',
                   FinancialIndex.LIBOR1M: 'US0001M INDEX',
                   FinancialIndex.LIBOR3M: 'US0003M INDEX',
                   FinancialIndex.LIBOR6M: 'US0006M INDEX',
                   FinancialIndex.LIBOR1Y: 'US0012M INDEX'}

# endregion


# region Configuración de Curvas

"""Configuración de Curvas"""
curve_config = {'AUD_CL.AUD': {'type': CurveType.DISCOUNT, 'currency': Currency.AUD, 'colateral': Currency.CLP},
                'CURVA_AUD_CL': {'type': CurveType.DISCOUNT, 'currency': Currency.AUD, 'colateral': Currency.CLP},
                'BRL_CL.BRL': {'type': CurveType.DISCOUNT, 'currency': Currency.BRL, 'colateral': Currency.CLP},
                'CURVA_BRL_CL': {'type': CurveType.DISCOUNT, 'currency': Currency.BRL, 'colateral': Currency.CLP},
                'CAD_CL.CAD': {'type': CurveType.DISCOUNT, 'currency': Currency.CAD, 'colateral': Currency.CLP},
                'CURVA_CAD_CL': {'type': CurveType.DISCOUNT, 'currency': Currency.CAD, 'colateral': Currency.CLP},
                'CHF_CL.CHF': {'type': CurveType.DISCOUNT, 'currency': Currency.CHF, 'colateral': Currency.CLP},
                'CURVA_CHF_CL': {'type': CurveType.DISCOUNT, 'currency': Currency.CHF, 'colateral': Currency.CLP},
                'CNY_CL.CNY': {'type': CurveType.DISCOUNT, 'currency': Currency.CNY, 'colateral': Currency.CLP},
                'CURVA_CNY_CL': {'type': CurveType.DISCOUNT, 'currency': Currency.CNY, 'colateral': Currency.CLP},
                'COP_CL.COP': {'type': CurveType.DISCOUNT, 'currency': Currency.COP, 'colateral': Currency.CLP},
                'CURVA_COP_CL': {'type': CurveType.DISCOUNT, 'currency': Currency.COP, 'colateral': Currency.CLP},
                'DKK_CL.DKK': {'type': CurveType.DISCOUNT, 'currency': Currency.DKK, 'colateral': Currency.CLP},
                'CURVA_DKK_CL': {'type': CurveType.DISCOUNT, 'currency': Currency.DKK, 'colateral': Currency.CLP},
                'EUR_CL.EUR': {'type': CurveType.DISCOUNT, 'currency': Currency.EUR, 'colateral': Currency.CLP},
                'CURVA_EUR_CL': {'type': CurveType.DISCOUNT, 'currency': Currency.EUR, 'colateral': Currency.CLP},
                'GBP_CL.GBP': {'type': CurveType.DISCOUNT, 'currency': Currency.GBP, 'colateral': Currency.CLP},
                'CURVA_GBP_CL': {'type': CurveType.DISCOUNT, 'currency': Currency.GBP, 'colateral': Currency.CLP},
                'HKD_CL.HKD': {'type': CurveType.DISCOUNT, 'currency': Currency.HKD, 'colateral': Currency.CLP},
                'JPY_CL.JPY': {'type': CurveType.DISCOUNT, 'currency': Currency.JPY, 'colateral': Currency.CLP},
                'CURVA_JPY_CL': {'type': CurveType.DISCOUNT, 'currency': Currency.JPY, 'colateral': Currency.CLP},
                'MXN_CL.MXN': {'type': CurveType.DISCOUNT, 'currency': Currency.MXN, 'colateral': Currency.CLP},
                'CURVA_MXN_CL': {'type': CurveType.DISCOUNT, 'currency': Currency.MXN, 'colateral': Currency.CLP},
                'NOK_CL.NOK': {'type': CurveType.DISCOUNT, 'currency': Currency.NOK, 'colateral': Currency.CLP},
                'CURVA_NOK_CL': {'type': CurveType.DISCOUNT, 'currency': Currency.NOK, 'colateral': Currency.CLP},
                'NZD_CL.NZD': {'type': CurveType.DISCOUNT, 'currency': Currency.NZD, 'colateral': Currency.CLP},
                'CURVA_NZD_CL': {'type': CurveType.DISCOUNT, 'currency': Currency.NZD, 'colateral': Currency.CLP},
                'PEN_CL.PEN': {'type': CurveType.DISCOUNT, 'currency': Currency.PEN, 'colateral': Currency.CLP},
                'CURVA_PEN_CL': {'type': CurveType.DISCOUNT, 'currency': Currency.PEN, 'colateral': Currency.CLP},
                'SEK_CL.SEK': {'type': CurveType.DISCOUNT, 'currency': Currency.SEK, 'colateral': Currency.CLP},
                'CURVA_SEK_CL': {'type': CurveType.DISCOUNT, 'currency': Currency.SEK, 'colateral': Currency.CLP},
                'CURVA_USD_CL': {'type': CurveType.DISCOUNT, 'currency': Currency.USD, 'colateral': Currency.CLP},
                'ZAR_CL.ZAR': {'type': CurveType.DISCOUNT, 'currency': Currency.ZAR, 'colateral': Currency.CLP},
                'CURVA_ZAR_CL': {'type': CurveType.DISCOUNT, 'currency': Currency.ZAR, 'colateral': Currency.CLP},
                'CURVA_KRW_CL': {'type': CurveType.DISCOUNT, 'currency': Currency.KRW, 'colateral': Currency.CLP},
                'AUD FX': {'type': CurveType.DISCOUNT, 'currency': Currency.AUD, 'colateral': Currency.USD},
                'CURVA_AUD_USD': {'type': CurveType.DISCOUNT, 'currency': Currency.AUD, 'colateral': Currency.USD},
                'BRL FX': {'type': CurveType.DISCOUNT, 'currency': Currency.BRL, 'colateral': Currency.USD},
                'CURVA_BRL_USD': {'type': CurveType.DISCOUNT, 'currency': Currency.BRL, 'colateral': Currency.USD},
                'CAD FX': {'type': CurveType.DISCOUNT, 'currency': Currency.CAD, 'colateral': Currency.USD},
                'CURVA_CAD_USD': {'type': CurveType.DISCOUNT, 'currency': Currency.CAD, 'colateral': Currency.USD},
                'CHF FX': {'type': CurveType.DISCOUNT, 'currency': Currency.CHF, 'colateral': Currency.USD},
                'CURVA_CHF_USD': {'type': CurveType.DISCOUNT, 'currency': Currency.CHF, 'colateral': Currency.USD},
                'CLP FX': {'type': CurveType.DISCOUNT, 'currency': Currency.CLP, 'colateral': Currency.USD},
                'CURVA_CLP_USD': {'type': CurveType.DISCOUNT, 'currency': Currency.CLP, 'colateral': Currency.USD},
                'CNH FX': {'type': CurveType.DISCOUNT, 'currency': Currency.CNH, 'colateral': Currency.USD},
                'CURVA_CNH_USD': {'type': CurveType.DISCOUNT, 'currency': Currency.CNH, 'colateral': Currency.USD},
                'CNY FX': {'type': CurveType.DISCOUNT, 'currency': Currency.CNY, 'colateral': Currency.USD},
                'CURVA_CNY_USD': {'type': CurveType.DISCOUNT, 'currency': Currency.CNY, 'colateral': Currency.USD},
                'COP FX': {'type': CurveType.DISCOUNT, 'currency': Currency.COP, 'colateral': Currency.USD},
                'CURVA_COP_USD': {'type': CurveType.DISCOUNT, 'currency': Currency.COP, 'colateral': Currency.USD},
                'DKK FX': {'type': CurveType.DISCOUNT, 'currency': Currency.DKK, 'colateral': Currency.USD},
                'CURVA_DKK_USD': {'type': CurveType.DISCOUNT, 'currency': Currency.DKK, 'colateral': Currency.USD},
                'EUR FX': {'type': CurveType.DISCOUNT, 'currency': Currency.EUR, 'colateral': Currency.USD},
                'CURVA_EUR_USD': {'type': CurveType.DISCOUNT, 'currency': Currency.EUR, 'colateral': Currency.USD},
                'GBP FX': {'type': CurveType.DISCOUNT, 'currency': Currency.GBP, 'colateral': Currency.USD},
                'CURVA_GBP_USD': {'type': CurveType.DISCOUNT, 'currency': Currency.GBP, 'colateral': Currency.USD},
                'HKD FX': {'type': CurveType.DISCOUNT, 'currency': Currency.HKD, 'colateral': Currency.USD},
                'CURVA_HKD_USD': {'type': CurveType.DISCOUNT, 'currency': Currency.HKD, 'colateral': Currency.USD},
                'JPY FX': {'type': CurveType.DISCOUNT, 'currency': Currency.JPY, 'colateral': Currency.USD},
                'CURVA_JPY_USD': {'type': CurveType.DISCOUNT, 'currency': Currency.JPY, 'colateral': Currency.USD},
                'KRW FX': {'type': CurveType.DISCOUNT, 'currency': Currency.KRW, 'colateral': Currency.USD},
                'CURVA_KRW_USD': {'type': CurveType.DISCOUNT, 'currency': Currency.KRW, 'colateral': Currency.USD},
                'MXN FX': {'type': CurveType.DISCOUNT, 'currency': Currency.MXN, 'colateral': Currency.USD},
                'CURVA_MXN_USD': {'type': CurveType.DISCOUNT, 'currency': Currency.MXN, 'colateral': Currency.USD},
                'NOK FX': {'type': CurveType.DISCOUNT, 'currency': Currency.NOK, 'colateral': Currency.USD},
                'CURVA_NOK_USD': {'type': CurveType.DISCOUNT, 'currency': Currency.NOK, 'colateral': Currency.USD},
                'NZD FX': {'type': CurveType.DISCOUNT, 'currency': Currency.NZD, 'colateral': Currency.USD},
                'CURVA_NZD_USD': {'type': CurveType.DISCOUNT, 'currency': Currency.NZD, 'colateral': Currency.USD},
                'PEN FX': {'type': CurveType.DISCOUNT, 'currency': Currency.PEN, 'colateral': Currency.USD},
                'CURVA_PEN_USD': {'type': CurveType.DISCOUNT, 'currency': Currency.PEN, 'colateral': Currency.USD},
                'SEK FX': {'type': CurveType.DISCOUNT, 'currency': Currency.SEK, 'colateral': Currency.USD},
                'CURVA_SEK_USD': {'type': CurveType.DISCOUNT, 'currency': Currency.SEK, 'colateral': Currency.USD},
                'ZAR FX': {'type': CurveType.DISCOUNT, 'currency': Currency.ZAR, 'colateral': Currency.USD},
                'CURVA_ZAR_USD': {'type': CurveType.DISCOUNT, 'currency': Currency.ZAR, 'colateral': Currency.USD},
                'INTERBANCARIA.CLF': {'type': CurveType.DUAL, 'currency': Currency.CLF, 'colateral': Currency.CLP,
                                      'index': FinancialIndex.ICP_REAL},
                'CURVA_CLF_CL': {'type': CurveType.DUAL, 'currency': Currency.CLF, 'colateral': Currency.CLP,
                                 'index': FinancialIndex.ICP_REAL},
                'INTERBANCARIA.CLP': {'type': CurveType.DUAL, 'currency': Currency.CLP, 'colateral': Currency.CLP,
                                      'index': FinancialIndex.ICP},
                'CURVA_CLP_CL': {'type': CurveType.DUAL, 'currency': Currency.CLP, 'colateral': Currency.CLP,
                                 'index': FinancialIndex.ICP},
                'CLP_CAM': {'type': CurveType.DUAL, 'currency': Currency.CLP, 'colateral': Currency.CLP,
                            'index': FinancialIndex.ICP},
                'OIS.USD': {'type': CurveType.DUAL, 'currency': Currency.USD, 'colateral': Currency.CLP,
                            'index': FinancialIndex.SOFR},
                'EONIA.EUR': {'type': CurveType.DUAL, 'currency': Currency.EUR, 'colateral': Currency.EUR,
                              'index': FinancialIndex.ESTR},
                'CURVA_EUR_EU': {'type': CurveType.DUAL, 'currency': Currency.EUR, 'colateral': Currency.EUR,
                                 'index': FinancialIndex.ESTR},
                'CLF :STD': {'type': CurveType.DUAL, 'currency': Currency.CLF, 'colateral': Currency.USD,
                             'index': FinancialIndex.ICP_REAL},
                'CURVA_UF_USD': {'type': CurveType.DUAL, 'currency': Currency.CLF, 'colateral': Currency.USD,
                                 'index': FinancialIndex.ICP_REAL},
                'CURVA_CLF_USD': {'type': CurveType.DUAL, 'currency': Currency.CLF, 'colateral': Currency.USD,
                                  'index': FinancialIndex.ICP_REAL},
                'CURVA_USD_USA': {'type': CurveType.DUAL, 'currency': Currency.USD, 'colateral': Currency.USD,
                                  'index': FinancialIndex.SOFR},
                'USD SOFR': {'type': CurveType.DUAL, 'currency': Currency.USD, 'colateral': Currency.USD,
                             'index': FinancialIndex.SOFR},
                'AUD AONIA': {'type': CurveType.PROJECTION,  'index': FinancialIndex.AONIA},
                'AUD BBSW 3M': {'type': CurveType.PROJECTION,  'index': FinancialIndex.BBSW_3M},
                'CHF SARON': {'type': CurveType.PROJECTION,  'index': FinancialIndex.SARON},
                'CLF TAB 1Y': {'type': CurveType.PROJECTION,  'index': FinancialIndex.TABUF1Y},
                'CLF TAB 3M': {'type': CurveType.PROJECTION,  'index': FinancialIndex.TABUF3M},
                'CLF TAB 6M': {'type': CurveType.PROJECTION,  'index': FinancialIndex.TABUF6M},
                'CLP TAB 1M': {'type': CurveType.PROJECTION,  'index': FinancialIndex.TAB1M},
                'CLP TAB 1Y': {'type': CurveType.PROJECTION, 'index': FinancialIndex.TAB1Y},
                'CLP TAB 3M': {'type': CurveType.PROJECTION, 'index': FinancialIndex.TAB3M},
                'CLP TAB 6M': {'type': CurveType.PROJECTION, 'index': FinancialIndex.TAB6M},
                'COP IBR': {'type': CurveType.PROJECTION, 'index': FinancialIndex.IBR},
                'EUR ESTR': {'type': CurveType.PROJECTION, 'index': FinancialIndex.ESTR},
                'JPY TONA': {'type': CurveType.PROJECTION, 'index': FinancialIndex.TONA},
                'EUR EURIBOR 6M': {'type': CurveType.PROJECTION, 'index': FinancialIndex.EURIBOR6M},
                'LIBOR12M.USD': {'type': CurveType.PROJECTION,  'index': FinancialIndex.LIBOR1Y},
                'LIBOR1M.USD': {'type': CurveType.PROJECTION,  'index': FinancialIndex.LIBOR1M},
                'LIBOR3M.USD': {'type': CurveType.PROJECTION,  'index': FinancialIndex.LIBOR3M},
                'LIBOR6M.USD': {'type': CurveType.PROJECTION,  'index': FinancialIndex.LIBOR6M},
                'LIBOROFFSHORE.EUR': {'type': CurveType.PROJECTION,  'index': FinancialIndex.EURIBOR3M},
                'LIBOROFFSHORE_12M.EUR': {'type': CurveType.PROJECTION,  'index': FinancialIndex.EURIBOR1Y},
                'LIBOROFFSHORE_1M.EUR': {'type': CurveType.PROJECTION,  'index': FinancialIndex.EURIBOR1M},
                'LIBOROFFSHORE_6M.EUR': {'type': CurveType.PROJECTION,  'index': FinancialIndex.EURIBOR6M},
                'TAB180.CLF': {'type': CurveType.PROJECTION,  'index': FinancialIndex.TABUF6M},
                'TAB180.CLP': {'type': CurveType.PROJECTION,  'index': FinancialIndex.TAB6M},
                'TAB30.CLP': {'type': CurveType.PROJECTION,  'index': FinancialIndex.TAB1M},
                'TAB360.CLF': {'type': CurveType.PROJECTION,  'index': FinancialIndex.TABUF1Y},
                'TAB360.CLP': {'type': CurveType.PROJECTION,  'index': FinancialIndex.TAB1Y},
                'TAB90.CLF': {'type': CurveType.PROJECTION,  'index': FinancialIndex.TABUF3M},
                'TAB90.CLP': {'type': CurveType.PROJECTION,  'index': FinancialIndex.TAB3M},
                'CURVA_EURIBOR1M': {'type': CurveType.PROJECTION,  'index': FinancialIndex.EURIBOR1M},
                'CURVA_EURIBOR1Y': {'type': CurveType.PROJECTION,  'index': FinancialIndex.EURIBOR1Y},
                'CURVA_EURIBOR3M': {'type': CurveType.PROJECTION,  'index': FinancialIndex.EURIBOR3M},
                'CURVA_EURIBOR6M': {'type': CurveType.PROJECTION,  'index': FinancialIndex.EURIBOR6M},
                'CURVA_LIBOR1M': {'type': CurveType.PROJECTION,  'index': FinancialIndex.LIBOR1M},
                'CURVA_LIBOR1Y': {'type': CurveType.PROJECTION,  'index': FinancialIndex.LIBOR1Y},
                'CURVA_LIBOR3M': {'type': CurveType.PROJECTION,  'index': FinancialIndex.LIBOR3M},
                'CURVA_LIBOR6M': {'type': CurveType.PROJECTION,  'index': FinancialIndex.LIBOR6M},
                'CURVA_TABCLF1Y': {'type': CurveType.PROJECTION,  'index': FinancialIndex.TABUF1Y},
                'CURVA_TABCLF3M': {'type': CurveType.PROJECTION,  'index': FinancialIndex.TABUF3M},
                'CURVA_TABCLF6M': {'type': CurveType.PROJECTION,  'index': FinancialIndex.TABUF6M},
                'CURVA_TABCLP1M': {'type': CurveType.PROJECTION,  'index': FinancialIndex.TAB1M},
                'CURVA_TABCLP1Y': {'type': CurveType.PROJECTION,  'index': FinancialIndex.TAB1Y},
                'CURVA_TABCLP3M': {'type': CurveType.PROJECTION,  'index': FinancialIndex.TAB3M},
                'CURVA_TABCLP6M': {'type': CurveType.PROJECTION,  'index': FinancialIndex.TAB6M},
                # CURVAS NUEVAS
                'CURVA_AONIA': {'type': CurveType.PROJECTION,  'index': FinancialIndex.AONIA},
                'CURVA_BBSW3M': {'type': CurveType.PROJECTION,  'index': FinancialIndex.BBSW_3M},
                'CURVA_SARON': {'type': CurveType.PROJECTION,  'index': FinancialIndex.SARON},
                'CURVA_TONA': {'type': CurveType.PROJECTION,  'index': FinancialIndex.TONA},

                'CURVA_HKD_CL': {'type': CurveType.FUNDING_COST},
                # CURVAS NUEVAS
                'USD LIBOR 1M': {'type': CurveType.PROJECTION,  'index': FinancialIndex.LIBOR1M},
                'USD LIBOR 1Y': {'type': CurveType.PROJECTION,  'index': FinancialIndex.LIBOR1Y},
                'USD LIBOR 3M': {'type': CurveType.PROJECTION,  'index': FinancialIndex.LIBOR3M},
                'USD LIBOR 6M': {'type': CurveType.PROJECTION,  'index': FinancialIndex.LIBOR6M},
                'CURVA_CLF_GOB_CL': {'type': CurveType.FIXED_INCOME},
                'CURVA_CLP_GOB_CL': {'type': CurveType.FIXED_INCOME},
                'CURVABCP': {'type': CurveType.FIXED_INCOME},
                'CURVABCU': {'type': CurveType.FIXED_INCOME},
                'CURVA_CF_CORP': {'type': CurveType.FUNDING_COST},
                'CURVA_CLF_CF': {'type': CurveType.FUNDING_COST},
                'CURVA_CLP_CF': {'type': CurveType.FUNDING_COST},
                'CURVA_USD_CF': {'type': CurveType.FUNDING_COST},
                'CURVA_SUB_CORP': {'type': CurveType.FUNDING_COST},
                'IBR.COP': {'type': CurveType.NOT_USED},
                'LIBOR_CLP_6M.USD': {'type': CurveType.NOT_USED},
                'LIBOR_USD_3M.AUD': {'type': CurveType.NOT_USED},
                'LIBOR_USD_3M.BRL': {'type': CurveType.NOT_USED},
                'LIBOR_USD_3M.CAD': {'type': CurveType.NOT_USED},
                'LIBOR_USD_3M.CHF': {'type': CurveType.NOT_USED},
                'LIBOR_USD_3M.CNY': {'type': CurveType.NOT_USED},
                'LIBOR_USD_3M.COP': {'type': CurveType.NOT_USED},
                'LIBOR_USD_3M.DKK': {'type': CurveType.NOT_USED},
                'LIBOR_USD_3M.EUR': {'type': CurveType.NOT_USED},
                'LIBOR_USD_3M.GBP': {'type': CurveType.NOT_USED},
                'LIBOR_USD_3M.HKD': {'type': CurveType.NOT_USED},
                'LIBOR_USD_3M.JPY': {'type': CurveType.NOT_USED},
                'LIBOR_USD_3M.MXN': {'type': CurveType.NOT_USED},
                'LIBOR_USD_3M.NOK': {'type': CurveType.NOT_USED},
                'LIBOR_USD_3M.NZD': {'type': CurveType.NOT_USED},
                'LIBOR_USD_3M.PEN': {'type': CurveType.NOT_USED},
                'LIBOR_USD_3M.SEK': {'type': CurveType.NOT_USED},
                'LIBOR_USD_3M.ZAR': {'type': CurveType.NOT_USED},
                'CURVA_CF_SANT': {'type': CurveType.NOT_USED},
                'OIS_USD.COP': {'type': CurveType.NOT_USED},
                'CURVA_COLTES': {'type': CurveType.NOT_USED},
                'CURVA_COP_CO': {'type': CurveType.NOT_USED},
                'CLP ICP': {'type': CurveType.NOT_USED},
                'CLP TAB CLF': {'type': CurveType.NOT_USED},
                'CLP TAB CLP': {'type': CurveType.NOT_USED},
                'USD DAILY TERM SOFR': {'type': CurveType.NOT_USED},
                'USD OIS': {'type': CurveType.NOT_USED},
                'CURVA_MXN_TIIE': {'type': CurveType.NOT_USED},
                'CURVA_SUB_SANT': {'type': CurveType.NOT_USED},
                'CURVA_USD_USA2': {'type': CurveType.NOT_USED},
                'CURVABR': {'type': CurveType.NOT_USED},
                'CURVACEROS': {'type': CurveType.NOT_USED},
                'CURVADPD': {'type': CurveType.NOT_USED},
                'CURVADPF1': {'type': CurveType.NOT_USED},
                'CURVADPF2': {'type': CurveType.NOT_USED},
                'CURVADPR': {'type': CurveType.NOT_USED},
                'CURVAFWAUD': {'type': CurveType.NOT_USED},
                'CURVAFWAUD_USA': {'type': CurveType.NOT_USED},
                'CURVAFWBRL': {'type': CurveType.NOT_USED},
                'CURVAFWBRL_USA': {'type': CurveType.NOT_USED},
                'CURVAFWCAD': {'type': CurveType.NOT_USED},
                'CURVAFWCAD_USA': {'type': CurveType.NOT_USED},
                'CURVAFWCHF': {'type': CurveType.NOT_USED},
                'CURVAFWCHF_USA': {'type': CurveType.NOT_USED},
                'CURVAFWCLP': {'type': CurveType.NOT_USED},
                'CURVAFWCLP_USA': {'type': CurveType.NOT_USED},
                'CURVAFWCNY': {'type': CurveType.NOT_USED},
                'CURVAFWCNY_USA': {'type': CurveType.NOT_USED},
                'CURVAFWCOP': {'type': CurveType.NOT_USED},
                'CURVAFWCOP_USA': {'type': CurveType.NOT_USED},
                'CURVAFWDKK': {'type': CurveType.NOT_USED},
                'CURVAFWDKK_USA': {'type': CurveType.NOT_USED},
                'CURVAFWEUR': {'type': CurveType.NOT_USED},
                'CURVAFWEUR_USA': {'type': CurveType.NOT_USED},
                'CURVAFWGBP': {'type': CurveType.NOT_USED},
                'CURVAFWGBP_USA': {'type': CurveType.NOT_USED},
                'CURVAFWJPY': {'type': CurveType.NOT_USED},
                'CURVAFWJPY_USA': {'type': CurveType.NOT_USED},
                'CURVAFWKRW': {'type': CurveType.NOT_USED},
                'CURVAFWKRW_USA': {'type': CurveType.NOT_USED},
                'CURVAFWMXN': {'type': CurveType.NOT_USED},
                'CURVAFWMXN_USA': {'type': CurveType.NOT_USED},
                'CURVAFWNOK': {'type': CurveType.NOT_USED},
                'CURVAFWNOK_USA': {'type': CurveType.NOT_USED},
                'CURVAFWPEN': {'type': CurveType.NOT_USED},
                'CURVAFWPEN_USA': {'type': CurveType.NOT_USED},
                'CURVAFWSEK': {'type': CurveType.NOT_USED},
                'CURVAFWSEK_USA': {'type': CurveType.NOT_USED},
                'CURVAFWUF': {'type': CurveType.NOT_USED},
                'CURVAFWUF_USA': {'type': CurveType.NOT_USED},
                'CURVAFWUSD': {'type': CurveType.NOT_USED},
                'CURVAFWUSD_USA': {'type': CurveType.NOT_USED},
                'CURVALHCORP': {'type': CurveType.NOT_USED},
                'CURVALHEST': {'type': CurveType.NOT_USED},
                'CURVAPDBC': {'type': CurveType.NOT_USED},
                'CURVAPRC': {'type': CurveType.NOT_USED},
                'CURVASCUFUSD': {'type': CurveType.NOT_USED},
                'CURVASCUFUSD_USA': {'type': CurveType.NOT_USED},
                'CURVASWAPCLP': {'type': CurveType.NOT_USED},
                'CURVASWAPCOPCHI': {'type': CurveType.NOT_USED},
                'CURVASWAPCOPIBR': {'type': CurveType.NOT_USED},
                'CURVASWAPUSDLOCAL': {'type': CurveType.NOT_USED}
                }

# endregion
